"""
A2A (Agent-to-Agent) protocol endpoints (Issue #737 Phase 1).

Phase 1 surface: a single endpoint that returns each Trinity agent's
A2A v1.0 Agent Card. External orchestrators (AWS Bedrock, Azure
Copilot, Google ADK) consume the card to discover what the agent
can do without knowing Trinity's internal API.

The card is generated by the backend from the agent's `template.yaml`
+ ownership metadata — no agent-server changes required. The agent
container doesn't need to be running for a stopped agent's card to
be served; we fall back to the metadata carried on the Docker
container's labels, which survive `docker stop`.
"""

from __future__ import annotations

import logging

import httpx
from fastapi import APIRouter, HTTPException, Request

from dependencies import AuthorizedAgentByName
from services.a2a_card_service import generate_a2a_card
from services.docker_service import get_agent_container

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/agents", tags=["a2a"])


def _base_url_from_request(request: Request) -> str:
    """Compute the external base URL for card `url` construction.

    Order of preference:
      1. `PUBLIC_CHAT_URL` env if set — this is what external
         consumers reach Trinity through (Cloudflare tunnel, etc.).
      2. `FRONTEND_URL` env — second-best for self-hosted setups.
      3. The request's own scheme + host — works fine for clients
         that fetched the card from the same host they'll call.

    Returns "" if none of the above resolve, signalling the card
    generator to omit URL fields rather than emit a broken URL.
    """
    from config import FRONTEND_URL, PUBLIC_CHAT_URL  # local import: avoid circular at module load

    if PUBLIC_CHAT_URL:
        return PUBLIC_CHAT_URL.rstrip("/")
    if FRONTEND_URL:
        return FRONTEND_URL.rstrip("/")
    if request.url:
        return f"{request.url.scheme}://{request.url.netloc}"
    return ""


async def _fetch_template_data(agent_name: str, container) -> dict:
    """Fetch template.yaml data from the agent's container (when
    running) or fall back to docker labels (when stopped).

    Mirrors the existing `GET /api/agents/{name}/info` fallback logic
    so a stopped agent still produces a usable card. Network errors
    are logged and treated as "use the label fallback" — we never let
    a transient agent-server failure 5xx the card endpoint.
    """
    labels = container.labels or {}
    label_fallback = {
        "name": agent_name,
        "display_name": labels.get("trinity.template", agent_name),
        "description": "",
        "version": "1.0.0",
        "capabilities": [],
        "use_cases": [],
    }

    if container.status != "running":
        return label_fallback

    try:
        agent_url = f"http://agent-{agent_name}:8000/api/template/info"
        async with httpx.AsyncClient(timeout=5.0) as client:
            response = await client.get(agent_url)
            if response.status_code == 200:
                data = response.json()
                # The agent-server returns `has_template=False` when
                # the agent was created without a template.yaml. Use
                # the label fallback in that case so the card still
                # advertises the agent's name + provider, just with
                # an empty skills list.
                if data.get("has_template") is False:
                    return label_fallback
                return data
            logger.info(
                f"A2A card: agent-server /api/template/info returned "
                f"{response.status_code} for {agent_name}; using label fallback"
            )
    except httpx.TimeoutException:
        logger.info(f"A2A card: agent-server timeout for {agent_name}; using label fallback")
    except Exception as e:  # noqa: BLE001 — defensive: never 5xx the card
        logger.warning(f"A2A card: agent-server unreachable for {agent_name}: {e}")

    return label_fallback


@router.get("/{agent_name}/a2a/agent-card")
async def get_agent_card(
    agent_name: AuthorizedAgentByName,
    request: Request,
):
    """Return the A2A v1.0 Agent Card for `agent_name`.

    Auth: requires `AuthorizedAgentByName` (same gate as the rest of
    the per-agent endpoints — owner, admin, or shared user). The
    issue's "public card" framing refers to the *content* of the
    card (no sensitive fields), not unauthenticated access. Public
    serving via `/.well-known/agent-card.json` is a follow-up that
    needs a separate route + access-policy decision.

    404 if the agent doesn't exist or the caller doesn't have access.
    Card generation never 5xx's — agent-server failures fall back to
    Docker labels.
    """
    container = get_agent_container(agent_name)
    if not container:
        raise HTTPException(status_code=404, detail="Agent not found")

    template_data = await _fetch_template_data(agent_name, container)
    base_url = _base_url_from_request(request)
    card = generate_a2a_card(
        agent_name=agent_name,
        template_data=template_data,
        base_url=base_url,
    )
    return card
